steps:
  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    entrypoint: 'bash'
    args: ['pwd']
    # args: ['./build-image.sh']

  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    entrypoint: 'bash'
    args: ['ls', '-alth']

  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    entrypoint: 'bash'
    args: ['find', '.', '-name', 'cloudbuild.yaml']

artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths:
      - 'tmp-newlib/deploy/images/nrf52840dk-nrf52840/*.elf'
