steps:
  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    args:
      - -c
      - |
        pwd
        ls -alth
        find . -name cloudbuild.yaml
        git submodule init
        git submodule update
        ./build-image.sh

artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths:
      - 'tmp-newlib/deploy/images/nrf52840dk-nrf52840/*.elf'
