steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update

  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone2'
    entrypoint: "bash"
    args:
      - '-c'
      - |
        ./build-image.sh

artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths:
      - 'tmp-newlib/deploy/images/nrf52840dk-nrf52840/*.elf'
