steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update

  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    entrypoint: "bash"
    dir: "/home/yocto"
    timeout: 7200s
    args:
      - '-c'
      - |
        source /workspace/submodule/poky/oe-init-build-env
        cp /workspace/yocto-conf/* conf/.
        bitbake zephyr-blinky

  - name: 'gcr.io/cloud-builders/gsutil'
    timeout: 7200s
    entrypoint: "bash"
    args:
      - '-c'
      - |
        gsutil -m rsync -r /yocto-cache/sstate gs://bright-cabinet-405308_cloudbuild/yocto-cache/sstate

artifacts:
  objects:
    location: 'gs://bright-cabinet-405308_cloudbuild/yocto-cache/artifacts/'
    paths:
      - '/workspace/deploy/**/*.elf'
options:
  machineType: 'E2_HIGHCPU_8'
  volumes:
    - path: '/yocto-cache/sstate'
      name: 'yocto-cache-sstate'
    - path: '/workspace/deploy'
      name: 'yocto-artifacts'

