steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update
  - name: 'us-west2-docker.pkg.dev/bright-cabinet-405308/yocto-docker-repo/yocto-builder:kirkstone'
    entrypoint: "bash"
    dir: "/home/yocto"
    timeout: 7200s
    args:
      - '-c'
      - |
        /workspace/build-image.sh
        find . -name '*blinky*elf'
    env:
      - 'BASEMETAPATH=/workspace'

artifacts:
  objects:
    location: 'gs://bright-cabinet-405308_cloudbuild/yocto-cache/artifacts/'
    paths:
      - '*.elf'
      - '/home/yocto/build/sstate/*'
options:
  machineType: 'E2_HIGHCPU_8'
